---

version: 2

jobs:
  build:
    docker:
      - image: decidim/decidim@sha256:348fb1faa49cfe76ba7cbeafc67ca09002cf95f0ffa7a76eefa9d5b3774e0ee9
        environment:
          DATABASE_USERNAME: postgres

      - image: postgres
        environment:
          POSTGRES_USER: postgres

    working_directory: /app

    steps:
      - checkout

      - restore_cache:
          keys:
            - bundler-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: bundle install

      - save_cache:
          key: bundler-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - /usr/local/bundle

      - run:
          name: Install firefox
          command: |
            echo "deb http://ftp.us.debian.org/debian/ sid main" > /etc/apt/sources.list.d/firefox.list
            apt-get update
            apt-get install -y firefox

      - run:
          name: Install geckodriver
          command: |
            curl --silent --show-error --location --fail --retry 3 --output /tmp/geckodriver_linux64.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
            tar xvzf /tmp/geckodriver_linux64.tar.gz -C /usr/local/bin
            rm /tmp/geckodriver_linux64.tar.gz

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Generate test app
          command: bundle exec rake decidim:generate_external_test_app

      - run:
          name: Run RSpec tests
          command: bundle exec rspec

      - run:
          name: Run rubocop
          command: bundle exec rubocop

      - store_artifacts:
          path: /app/spec/decidim_dummy_app/tmp/screenshots

workflows:
  version: 2

  test:
    jobs:
      - build
