---

base_locale: en
locales: [en, es]

ignore_unused:
  - activemodel.attributes.gravity_form.description
  - "decidim.components.gravity_forms.*"

ignore_missing:
  - decidim.participatory_processes.scopes.global
