---

inherit_from:
  - https://raw.githubusercontent.com/decidim/decidim/0.11-stable/.rubocop.yml
  - https://raw.githubusercontent.com/decidim/decidim/0.11-stable/.rubocop_rails.yml

AllCops:
  Exclude:
    - db/schema.rb

Naming/FileName:
  Exclude:
    - config/initializers/decidim-census_connector.rb
    - config/initializers/decidim-collaborations.rb
    - Capfile
    - Gemfile
    - Rakefile

Rails/Output:
  Exclude:
    - lib/participa2/seeds/scopes.rb
