---

inherit_mode:
  merge:
    - Exclude

inherit_from:
  - https://raw.githubusercontent.com/decidim/decidim/0.12-stable/.rubocop.yml
  - https://raw.githubusercontent.com/decidim/decidim/0.12-stable/.rubocop_rails.yml

AllCops:
  Exclude:
    - db/schema.rb
    - "**/spec/decidim_dummy_app/**/*"

Naming/FileName:
  Exclude:
    - decidim-module-census_connector/lib/generators/decidim/census_connector/install/templates/config/initializers/decidim-census_connector.rb
    - config/initializers/decidim-census_connector.rb
    - config/initializers/decidim-crowdfundings.rb
    - Capfile
    - Gemfile
    - Rakefile

Rails/Output:
  Exclude:
    - decidim-module-census_connector/lib/decidim/census_connector/seeds/scopes.rb

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/spec/**/*"
