---

version: 2

jobs:
  build:
    docker:
      - image: ruby:2.5.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - bundler-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: bundle install

      - save_cache:
          key: bundler-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - /usr/local/bundle

      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install yarn dependencies
          command: yarn install

      - save_cache:
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Run tests
          command: bundle exec rspec

      - run:
          name: Run rubocop
          command: bundle exec rubocop

      - run:
          name: Run yarn lints
          command: yarn lint

      - add_ssh_keys:
          fingerprints:
            - "43:69:49:83:52:61:1b:5c:e4:2c:3c:2b:ea:7b:8f:32"

      - deploy:
          command: bin/deploy-staging.sh
