---

version: "2"

plugins:
  grep:
    enabled: true

    config:
      patterns:
        no-trailing-whitespace:
          pattern: \s*$
          annotation: "Don't leave trailing whitespace"
          severity: minor
          categories: Style

        no-tabs:
          pattern: "	"
          annotation: "Don't use hard tabs"
          severity: minor
          categories: Style

  markdownlint:
    enabled: true

exclude_patterns:
  - development_app
  - spec/decidim_dummy_app
  - spec/fixtures
  - coverage
  - db/seeds
