default: &default
  airbrake:
    api_key: <%= ENV["AIRBRAKE_API_KEY"] %>
    project_id: <%= ENV["AIRBRAKE_PROJECT_ID"] %>
    host: <%= ENV["AIRBRAKE_HOST"] %>
  census:
    api_debug: <%= ENV["CENSUS_API_DEBUG"] %>
    api_base_uri: <%= ENV["CENSUS_URL"] %>
  geocoder:
    here_app_id: <%= ENV["GEOCODER_LOOKUP_APP_ID"] %>
    here_app_code: <%= ENV["GEOCODER_LOOKUP_APP_CODE"] %>
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  social_networks:
    facebook:
      name: "Facebook"
      url: "https://www.facebook.com/%{nickname}"
      nickname_validation: ^([a-zA-Z\d.]{5,})$
    twitter:
      name: "Twitter"
      url: "https://twitter.com/%{nickname}"
      nickname_validation: ^@?(\w{1,15})$
    instagram:
      name: "Instagram"
      url: "https://www.instagram.com/%{nickname}"
      nickname_validation: ^@?([a-zA-Z0-9_](?:(?:[a-zA-Z0-9_]|(?:\\.(?!\\.))){0,28}(?:[a-zA-Z0-9_]))?)$

development:
  <<: *default
  secret_key_base: e097d72e8aef38c95082f51b1c9211d39a9d51760e61d13c2be1b9918d4dafb8ffcf19158c572665be72bb6c0cece3a340cdabcbdd51e6035b52409a10f8ffbc

test:
  <<: *default
  secret_key_base: 69f9348ffba8c8436cf0bafac6410f68a5fc201946751558ec0df66ca3ca53b0d421e054b8b75e0c35d1d0a2f74bac0018c0061712f422f9fb64b9b25c282e7b
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

staging:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid: <%= !ENV["SENDGRID_USERNAME"].blank? %>
  smtp_username: <%= ENV["SMTP_USERNAME"] || ENV["SENDGRID_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] || ENV["SENDGRID_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] || "smtp.sendgrid.net" %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] || "heroku.com" %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
